### ISSUE TITLE
Policing In The Pandemic

### ISSUE THREAD

**Issue by xxristoskk** [qri-io/data-stories-scripts#30]
Collecting data/maintaining current datasets for a story that investigates the rate in which people are being taken into police custody and the rate of infection in jails and prisons. So far I have the the data for rate of confirmed COVID-19 cases, and data for inmates in custody within NYC jailes. Currently searching for more data on people being taken into custody data on COVID-19 cases within the police departments as well.

**Comment by b5** [comment]
From @xxristoskk:

* NYC open data is great. got it.
* Minneapolis (sp?) is _not_ open, I've put in a request, should hear back in 10 days
* Looking into LA, Detroit & a few areas that are known to have a history of racial tension between citizens & the police.

**Comment by xxristoskk** [comment]
Added rows to the weekly updated COVID-19 in Prisons dataset and got the following error when publishing.

`Put "https://registry.qri.cloud/remote/dsync?sid=odHhvFfmhc&hash=QmbBceqhrtupu7eumMBdykRMNhCVWcXYqFHsnUzRhrRjpK": stream error: stream ID 317; PROTOCOL_ERROR`

**Comment by xxristoskk** [comment]
Still waiting to hear back from the cities I mentioned, but found some open data from Chicago, LA, and Boston that is really useful. Going to write up some transcript code to maintain those datasets individually, run analysis on them, and create viz for each city. Gonna have the datastory ready for review on Thursday.

**Comment by xxristoskk** [comment]
For the weekend:
- [ ] Finish Analysis
- [ ] Create viz
- [ ] Create transform scripts
- [ ] Finish final datastory draft
