### ISSUE TITLE
Data Story: Band Camp NY Local Scenes

### ISSUE THREAD

**Issue by chriswhong** [qri-io/data-stories-scripts#9]
Working on a web map to complement @xxristoskk's Band Camp dataset and blog post

**Comment by xxristoskk** [comment]
Working on fixing the headers in the body.csv on Qri; they're being shifted around when the original csv is published on Qri Cloud.

**Comment by chriswhong** [comment]
Closing, this story is up! https://medium.com/qri-io/mapping-the-local-scenes-72fdd7392539?source=collection_home---6------0-----------------------
